<?php
session_start();
include('db_config.php');

$is_guard = isset($_SESSION['clerk_user']) && 
            isset($_SESSION['role']) && 
            $_SESSION['role'] === 'guard';

if (!$is_guard) {
    header("Location: login.php");
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Gate Control</title>
    <script src="https://unpkg.com/html5-qrcode"></script>
    <style>
        :root {
            --portal-blue: #1e3d8f;
            --portal-dark: #223a5e;
            --bg-light: #f4f6f9;
            --text-main: #2d3748;
            --success-green: #10b981;
            --success-hover: #059669;
            --border-color: #e2e8f0;
        }

        body {
            font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
            margin: 0;
            padding: 20px;
            background: linear-gradient(135deg, #f4f6f9 0%, #e2e8f0 100%);
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            color: var(--text-main);
            box-sizing: border-box;
        }

        /* Premium Container Frame */
        .container {
            background: #ffffff;
            width: 100%;
            max-width: 460px;
            border-radius: 16px;
            box-shadow: 0 10px 30px rgba(34, 58, 94, 0.08), 0 1px 3px rgba(0, 0, 0, 0.02);
            overflow: hidden;
            border: 1px solid var(--border-color);
            padding: 0; 
            text-align: left;
        }

        /* High Contrast Header Matching Login Accent */
        .card-header {
            background: linear-gradient(135deg, var(--portal-blue) 0%, var(--portal-dark) 100%);
            color: #ffffff;
            padding: 24px;
            text-align: center;
            border-bottom: 4px solid var(--success-green);
        }

        .card-header h2 {
            margin: 0 0 14px 0;
            font-size: 22px;
            font-weight: 700;
            letter-spacing: -0.5px;
        }

        /* Appealing Access History Logs Link Button */
        .btn-logs-link {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            color: rgba(255, 255, 255, 0.9);
            text-decoration: none;
            font-size: 13px;
            font-weight: 600;
            background: rgba(255, 255, 255, 0.12);
            padding: 8px 16px;
            border: 1px solid rgba(255, 255, 255, 0.2);
            border-radius: 20px;
            transition: all 0.2s ease;
        }

        .btn-logs-link:hover {
            background: #ffffff;
            color: var(--portal-blue);
            border-color: #ffffff;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .card-body {
            padding: 30px;
        }

        /* Position Dropdown Section Wrapper */
        .gate-config {
            background: #f8fafc;
            border: 1px solid var(--border-color);
            border-left: 4px solid var(--portal-blue);
            padding: 16px;
            border-radius: 8px;
            margin-bottom: 24px;
        }

        label {
            display: block;
            font-size: 12px;
            text-transform: uppercase;
            font-weight: 700;
            color: var(--portal-dark);
            letter-spacing: 0.5px;
            margin-bottom: 6px;
        }

        select {
            width: 100%;
            padding: 10px 14px;
            border: 1px solid var(--border-color);
            border-radius: 6px;
            font-size: 15px;
            font-weight: 600;
            color: var(--text-main);
            background-color: #ffffff;
            outline: none;
            cursor: pointer;
            box-sizing: border-box;
            transition: border-color 0.15s ease;
        }

        select:focus {
            border-color: var(--portal-blue);
        }

        /* Camera Box Wrapper Adjustment */
        #reader {
            width: 100%;
            border-radius: 12px;
            overflow: hidden;
            margin-bottom: 12px;
            border: 2px dashed #cbd5e1 !important;
            background: #fafbfc;
            transition: all 0.2s ease;
        }

        #reader:hover {
            border-color: var(--portal-blue) !important;
        }

        /* Style the inside buttons generated by the external scan library */
        #reader button {
            background: var(--portal-blue) !important;
            color: white !important;
            border: none !important;
            padding: 10px 22px !important;
            border-radius: 6px !important;
            font-weight: 600 !important;
            font-size: 14px !important;
            cursor: pointer !important;
            transition: background 0.2s ease !important;
            box-shadow: 0 4px 10px rgba(30, 61, 143, 0.15);
            margin: 10px 0 !important;
        }

        #reader button:hover {
            background: var(--portal-dark) !important;
        }

        #reader a {
            color: var(--portal-blue) !important;
            font-weight: 600;
            text-decoration: none;
        }

        .scan-caption {
            text-align: center;
            color: #475569;
            font-weight: bold;
            font-size: 14px;
            margin-top: 0;
            margin-bottom: 24px;
        }

        /* Separator Component styling */
        .divider {
            display: flex;
            align-items: center;
            text-align: center;
            color: #94a3b8;
            font-size: 11px;
            font-weight: 700;
            letter-spacing: 1px;
            margin: 24px 0;
            text-transform: uppercase;
        }

        .divider::before, .divider::after {
            content: '';
            flex: 1;
            border-bottom: 1px solid #e2e8f0;
        }

        .divider:not(:empty)::before { margin-right: 12px; }
        .divider:not(:empty)::after { margin-left: 12px; }

        /* Manual Input Segment fields */
        .manual-form label {
            display: block;
            font-size: 13px;
            font-weight: 600;
            margin-bottom: 8px;
            color: #475569;
            text-transform: none;
            letter-spacing: normal;
        }

        input[type="text"] {
            width: 100%;
            box-sizing: border-box;
            padding: 12px 16px;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            font-size: 15px;
            background-color: #f8fafc;
            outline: none;
            margin-bottom: 24px;
            transition: all 0.2s ease;
        }

        input[type="text"]:focus {
            background-color: #ffffff;
            border-color: var(--portal-blue);
            box-shadow: 0 0 0 3px rgba(30, 61, 143, 0.12);
        }

        /* Glowing Action Submission Button */
        .btn-submit {
            width: 100%;
            background: var(--success-green);
            color: #ffffff;
            border: none;
            padding: 14px;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 700;
            cursor: pointer;
            transition: all 0.2s ease;
            box-shadow: 0 4px 12px rgba(16, 185, 129, 0.25);
            letter-spacing: 0.3px;
        }

        .btn-submit:hover {
            background: var(--success-hover);
            transform: translateY(-1px);
            box-shadow: 0 6px 15px rgba(16, 185, 129, 0.3);
        }
        
        .btn-submit:active {
            transform: translateY(0);
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="card-header">
            <h2>Gate Control Panel</h2>
            <div style="display:flex; gap:8px; flex-wrap:wrap; justify-content:center;">
                <a href="guard_issue_guest_pass.php" class="btn-logs-link" style="background:rgba(124,58,237,0.2); border-color:rgba(124,58,237,0.4);">
                    🪪 Issue Guest Pass
                </a>
                <a href="attendance_dashboard.php" class="btn-logs-link">
                    🔍 View History Logs
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="gate-config">
                <label for="gate_selector">Current Active Gate Position</label>
                <select id="gate_selector" onchange="syncManualGate(this.value)">
                    <option value="Gate 1">Gate 1</option>
                    <option value="Gate 2">Gate 2</option>
                </select>
            </div>

            <div id="reader"></div>
            <p class="scan-caption">📷 Scan Student or Guest Pass QR</p>

            <div class="divider">OR MANUAL ENTRY</div>

            <form action="guard_scan_result.php" method="GET" class="manual-form">
                <input type="hidden" name="gate_no" id="manual_gate_hidden" value="Gate 1">

                <label>Unique ID (e.g. #E6)</label>
                <input type="text" name="id" placeholder="Enter Unique ID" required>

                <button type="submit" class="btn-submit">Log Entry / Exit</button>
            </form>
        </div>
    </div>

    <script>
        // Function to update hidden inputs when dropdown options are touched
        function syncManualGate(val) {
            let hiddenInput = document.getElementById('manual_gate_hidden');
            if (hiddenInput) {
                hiddenInput.value = val;
            }
        }

        // Force synchronizing default selected gate choice when browser rendering completes
        window.addEventListener('DOMContentLoaded', () => {
            let dropdown = document.getElementById('gate_selector');
            if (dropdown) {
                syncManualGate(dropdown.value);
            }
        });

        // Global block lock switch to prevent simultaneous double-scanning
        let isScanningAllowed = true;

        function onScanSuccess(decodedText) {
            // If a scan loop is already processing, drop subsequent camera capture tasks
            if (!isScanningAllowed) {
                return;
            }

            // Engage script thread execution lock instantly
            isScanningAllowed = false;

            // Clean up incoming unique ID raw strings perfectly
            let studentId = decodedText.includes('id=') ? decodedText.split('id=').pop() : decodedText;

            // Target dropdown element object references accurately
            let selectedGateElement = document.getElementById('gate_selector');
            let gateNo = selectedGateElement ? selectedGateElement.value : "Gate 1";

            // Map target data elements straight onto our query parameter tokens
            let targetUrl = "guard_scan_result.php?id=" + encodeURIComponent(studentId) + "&gate_no=" + encodeURIComponent(gateNo);

            // Shutdown camera lens preview streams prior to pushing routes
            html5QrcodeScanner.clear().then(() => {
                window.location.href = targetUrl;
            }).catch(err => {
                console.error("Scanner clear failed, routing target window fallback active:", err);
                window.location.href = targetUrl;
            });
        }

        // Initialize and bind active instances onto our reader viewport node
        let html5QrcodeScanner = new Html5QrcodeScanner("reader", { fps: 10, qrbox: 250 });
        html5QrcodeScanner.render(onScanSuccess);
    </script>

</body>

</html>